<?php

/**
 * @file
 * Set migrate_api.
 */

/**
 * Implements hook_migrate_migrate_api().
 *
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function tsitaatcom_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_init().
 */
function tsitaatcom_migrate_init() {
  if ($_GET['q'] === 'admin/content/migrate') {
    drupal_set_message(t('Note that author relations in quote nodes are made during TsitaatComAuthors import.'), 'status');
  }
}
